[package]
name = "cutr"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.27", features = ["derive"] }
csv = "1.3.1"
regex = "1.11.1"

[dev-dependencies]
anyhow = "1.0.95"
assert_cmd = "2.0.16"
predicates = "3.1.3"
pretty_assertions = "1.4.1"
rand = "=0.8.5"
