[package]
name = "echor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
assert_cmd = "2.0.16"
clap = "4.5.21"

[dev-dependencies]
assert_cmd = "2.0.16"
predicates = "3.1.2"
